//! Auto-transpiled C/C++ header module: BKE_callbacks

#[repr(C)]
#[derive(Debug, Clone, PartialEq, Default)]
pub struct bCallbackFuncStore {
    pub alloc: i16,
}

#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum eCbEvent {
    BKE_CB_EVT_FRAME_CHANGE_PRE,
    BKE_CB_EVT_FRAME_CHANGE_POST,
    BKE_CB_EVT_RENDER_PRE,
    BKE_CB_EVT_RENDER_POST,
    BKE_CB_EVT_RENDER_WRITE,
    BKE_CB_EVT_RENDER_STATS,
    BKE_CB_EVT_RENDER_INIT,
    BKE_CB_EVT_RENDER_COMPLETE,
    BKE_CB_EVT_RENDER_CANCEL,
    BKE_CB_EVT_LOAD_PRE,
    BKE_CB_EVT_LOAD_POST,
    BKE_CB_EVT_LOAD_POST_FAIL,
    BKE_CB_EVT_SAVE_PRE,
    BKE_CB_EVT_SAVE_POST,
    BKE_CB_EVT_SAVE_POST_FAIL,
    BKE_CB_EVT_UNDO_PRE,
    BKE_CB_EVT_UNDO_POST,
    BKE_CB_EVT_REDO_PRE,
    BKE_CB_EVT_REDO_POST,
    BKE_CB_EVT_DEPSGRAPH_UPDATE_PRE,
    BKE_CB_EVT_DEPSGRAPH_UPDATE_POST,
    BKE_CB_EVT_VERSION_UPDATE,
    BKE_CB_EVT_LOAD_FACTORY_USERDEF_POST,
    BKE_CB_EVT_LOAD_FACTORY_STARTUP_POST,
    BKE_CB_EVT_XR_SESSION_START_PRE,
    BKE_CB_EVT_ANNOTATION_PRE,
    BKE_CB_EVT_ANNOTATION_POST,
    BKE_CB_EVT_OBJECT_BAKE_PRE,
    BKE_CB_EVT_OBJECT_BAKE_COMPLETE,
    BKE_CB_EVT_OBJECT_BAKE_CANCEL,
    BKE_CB_EVT_COMPOSITE_PRE,
    BKE_CB_EVT_COMPOSITE_POST,
    BKE_CB_EVT_COMPOSITE_CANCEL,
    BKE_CB_EVT_ANIMATION_PLAYBACK_PRE,
    BKE_CB_EVT_ANIMATION_PLAYBACK_POST,
    BKE_CB_EVT_TRANSLATION_UPDATE_POST,
    BKE_CB_EVT_EXTENSION_REPOS_UPDATE_PRE,
    BKE_CB_EVT_EXTENSION_REPOS_UPDATE_POST,
    BKE_CB_EVT_EXTENSION_REPOS_SYNC,
    BKE_CB_EVT_EXTENSION_REPOS_FILES_CLEAR,
    BKE_CB_EVT_BLENDIMPORT_PRE,
    BKE_CB_EVT_BLENDIMPORT_POST,
    BKE_CB_EVT_EXIT_PRE,
    BKE_CB_EVT_TOT,
}
