//! Auto-transpiled C/C++ header module: DNA_lineart_types

#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum eLineartMainFlags {
    MOD_LINEART_INTERSECTION_AS_CONTOUR = (1 << 0),
    MOD_LINEART_EVERYTHING_AS_CONTOUR = (1 << 1),
    MOD_LINEART_ALLOW_DUPLI_OBJECTS = (1 << 2),
    MOD_LINEART_ALLOW_OVERLAPPING_EDGES = (1 << 3),
    MOD_LINEART_ALLOW_CLIPPING_BOUNDARIES = (1 << 4),
    MOD_LINEART_LOOSE_AS_CONTOUR = (1 << 6),
    MOD_LINEART_INVERT_SOURCE_VGROUP = (1 << 7),
    MOD_LINEART_MATCH_OUTPUT_VGROUP = (1 << 8),
    MOD_LINEART_FILTER_FACE_MARK = (1 << 9),
    MOD_LINEART_FILTER_FACE_MARK_INVERT = (1 << 10),
    MOD_LINEART_FILTER_FACE_MARK_BOUNDARIES = (1 << 11),
    MOD_LINEART_CHAIN_LOOSE_EDGES = (1 << 12),
    MOD_LINEART_CHAIN_GEOMETRY_SPACE = (1 << 13),
    MOD_LINEART_ALLOW_OVERLAP_EDGE_TYPES = (1 << 14),
    MOD_LINEART_USE_CREASE_ON_SMOOTH_SURFACES = (1 << 15),
    MOD_LINEART_USE_CREASE_ON_SHARP_EDGES = (1 << 16),
    MOD_LINEART_USE_CUSTOM_CAMERA = (1 << 17),
    MOD_LINEART_FILTER_FACE_MARK_KEEP_CONTOUR = (1 << 18),
    MOD_LINEART_USE_BACK_FACE_CULLING = (1 << 19),
    MOD_LINEART_USE_IMAGE_BOUNDARY_TRIMMING = (1 << 20),
    MOD_LINEART_CHAIN_PRESERVE_DETAILS = (1 << 22),
    MOD_LINEART_SHADOW_USE_SILHOUETTE = (1 << 24),
}

#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum eLineartEdgeFlag {
    MOD_LINEART_EDGE_FLAG_EDGE_MARK = (1 << 0),
    MOD_LINEART_EDGE_FLAG_CONTOUR = (1 << 1),
    MOD_LINEART_EDGE_FLAG_CREASE = (1 << 2),
    MOD_LINEART_EDGE_FLAG_MATERIAL = (1 << 3),
    MOD_LINEART_EDGE_FLAG_INTERSECTION = (1 << 4),
    MOD_LINEART_EDGE_FLAG_LOOSE = (1 << 5),
    MOD_LINEART_EDGE_FLAG_LIGHT_CONTOUR = (1 << 6),
    MOD_LINEART_EDGE_FLAG_PROJECTED_SHADOW = (1 << 8),
    MOD_LINEART_EDGE_FLAG_SHADOW_FACING_LIGHT = (1 << 9),
    MOD_LINEART_EDGE_FLAG_CHAIN_PICKED = (1 << 10),
    MOD_LINEART_EDGE_FLAG_CLIPPED = (1 << 11),
    MOD_LINEART_EDGE_FLAG_CONTOUR_SECONDARY = (1 << 12),
    MOD_LINEART_EDGE_FLAG_INHIBIT = (1 << 14),
    MOD_LINEART_EDGE_FLAG_NEXT_IS_DUPLICATION = (1 << 15),
}
