//! Auto-transpiled C/C++ header module: eevee_shader

use crate::*;

#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum eShaderType {
    AMBIENT_OCCLUSION_PASS = 0,
    FILM_COPY,
    FILM_COMP,
    FILM_COMP_PANORAMIC,
    FILM_CRYPTOMATTE_POST,
    FILM_FRAG,
    FILM_PASS_CONVERT_COMBINED,
    FILM_PASS_CONVERT_DEPTH,
    FILM_PASS_CONVERT_VALUE,
    FILM_PASS_CONVERT_COLOR,
    FILM_PASS_CONVERT_CRYPTOMATTE,
    DEFERRED_AOV_CLEAR,
    DEFERRED_CAPTURE_EVAL,
    DEFERRED_COMBINE,
    DEFERRED_LIGHT_SINGLE,
    DEFERRED_LIGHT_DOUBLE,
    DEFERRED_LIGHT_TRIPLE,
    DEFERRED_PLANAR_EVAL,
    DEFERRED_THICKNESS_AMEND,
    DEFERRED_TILE_CLASSIFY,
    DEFERRED_TILE_CLASSIFY_FALLBACK,
    DEBUG_GBUFFER,
    DEBUG_SURFELS,
    DEBUG_IRRADIANCE_GRID,
    DISPLAY_PROBE_VOLUME,
    DISPLAY_PROBE_SPHERE,
    DISPLAY_PROBE_PLANAR,
    DOF_BOKEH_LUT,
    DOF_DOWNSAMPLE,
    DOF_FILTER,
    DOF_GATHER_BACKGROUND_LUT,
    DOF_GATHER_BACKGROUND,
    DOF_GATHER_FOREGROUND_LUT,
    DOF_GATHER_FOREGROUND,
    DOF_GATHER_HOLE_FILL,
    DOF_REDUCE,
    DOF_RESOLVE_LUT,
    DOF_RESOLVE,
    DOF_SCATTER,
    DOF_SETUP,
    DOF_STABILIZE,
    DOF_TILES_DILATE_MINABS,
    DOF_TILES_DILATE_MINMAX,
    DOF_TILES_FLATTEN,
    HIZ_UPDATE,
    HIZ_UPDATE_LAYER,
    HIZ_DEBUG,
    FAST_GI_DENOISE,
    FAST_GI_RESOLVE,
    FAST_GI_SCAN,
    FAST_GI_SETUP,
    LIGHT_CULLING_DEBUG,
    LIGHT_CULLING_SELECT,
    LIGHT_CULLING_SORT,
    LIGHT_CULLING_TILE,
    LIGHT_CULLING_ZBIN,
    LIGHT_SHAPE_DISPLAY,
    LIGHT_SHADOW_SETUP,
    LIGHTPROBE_IRRADIANCE_BOUNDS,
    LIGHTPROBE_IRRADIANCE_OFFSET,
    LIGHTPROBE_IRRADIANCE_RAY,
    LIGHTPROBE_IRRADIANCE_LOAD,
    LIGHTPROBE_IRRADIANCE_WORLD,
    LOOKDEV_COPY_WORLD,
    LOOKDEV_DISPLAY,
    MOTION_BLUR_GATHER,
    MOTION_BLUR_TILE_DILATE,
    MOTION_BLUR_TILE_FLATTEN_RGBA,
    MOTION_BLUR_TILE_FLATTEN_RG,
    RAY_DENOISE_BILATERAL,
    RAY_DENOISE_SPATIAL,
    RAY_DENOISE_TEMPORAL,
    RAY_GENERATE,
    RAY_TILE_CLASSIFY,
    RAY_TILE_COMPACT,
    RAY_TRACE_FALLBACK,
    RAY_TRACE_PLANAR,
    RAY_TRACE_SCREEN,
    RENDERPASS_CLEAR,
    SPHERE_PROBE_CONVOLVE,
    SPHERE_PROBE_IRRADIANCE,
    SPHERE_PROBE_REMAP,
    SPHERE_PROBE_SELECT,
    SPHERE_PROBE_SUNLIGHT,
    SHADOW_CLIPMAP_CLEAR,
    SHADOW_DEBUG,
    SHADOW_PAGE_ALLOCATE,
    SHADOW_PAGE_CLEAR,
    SHADOW_PAGE_DEFRAG,
    SHADOW_PAGE_FREE,
    SHADOW_PAGE_MASK,
    SHADOW_TILEMAP_AMEND,
    SHADOW_TILEMAP_BOUNDS,
    SHADOW_TILEMAP_FINALIZE,
    SHADOW_TILEMAP_RENDERMAP,
    SHADOW_TILEMAP_INIT,
    SHADOW_TILEMAP_TAG_UPDATE,
    SHADOW_TILEMAP_TAG_UPDATE_PROPAGATE,
    SHADOW_TILEMAP_TAG_USAGE_OPAQUE,
    SHADOW_TILEMAP_TAG_USAGE_SURFELS,
    SHADOW_TILEMAP_TAG_USAGE_TRANSPARENT,
    SHADOW_TILEMAP_TAG_USAGE_VOLUME,
    SHADOW_VIEW_VISIBILITY,
    SUBSURFACE_CONVOLVE,
    SUBSURFACE_SETUP,
    SURFEL_CLUSTER_BUILD,
    SURFEL_LIGHT,
    SURFEL_LIST_BUILD,
    SURFEL_LIST_FLATTEN,
    SURFEL_LIST_PREFIX,
    SURFEL_LIST_PREPARE,
    SURFEL_LIST_SORT,
    SURFEL_RAY,
    TRANSPARENCY_RESOLVE,
    VERTEX_COPY,
    VOLUME_INTEGRATION,
    VOLUME_OCCUPANCY_CONVERT,
    VOLUME_RESOLVE,
    VOLUME_SCATTER,
    VOLUME_SCATTER_WITH_LIGHTS,
    MAX_SHADER_TYPE,
}

impl Default for eShaderType {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}

pub const AMBIENT_OCCLUSION_PASS: i32 = eShaderType::AMBIENT_OCCLUSION_PASS as i32;
pub const FILM_COPY: i32 = eShaderType::FILM_COPY as i32;
pub const FILM_COMP: i32 = eShaderType::FILM_COMP as i32;
pub const FILM_COMP_PANORAMIC: i32 = eShaderType::FILM_COMP_PANORAMIC as i32;
pub const FILM_CRYPTOMATTE_POST: i32 = eShaderType::FILM_CRYPTOMATTE_POST as i32;
pub const FILM_FRAG: i32 = eShaderType::FILM_FRAG as i32;
pub const FILM_PASS_CONVERT_COMBINED: i32 = eShaderType::FILM_PASS_CONVERT_COMBINED as i32;
pub const FILM_PASS_CONVERT_DEPTH: i32 = eShaderType::FILM_PASS_CONVERT_DEPTH as i32;
pub const FILM_PASS_CONVERT_VALUE: i32 = eShaderType::FILM_PASS_CONVERT_VALUE as i32;
pub const FILM_PASS_CONVERT_COLOR: i32 = eShaderType::FILM_PASS_CONVERT_COLOR as i32;
pub const FILM_PASS_CONVERT_CRYPTOMATTE: i32 = eShaderType::FILM_PASS_CONVERT_CRYPTOMATTE as i32;
pub const DEFERRED_AOV_CLEAR: i32 = eShaderType::DEFERRED_AOV_CLEAR as i32;
pub const DEFERRED_CAPTURE_EVAL: i32 = eShaderType::DEFERRED_CAPTURE_EVAL as i32;
pub const DEFERRED_COMBINE: i32 = eShaderType::DEFERRED_COMBINE as i32;
pub const DEFERRED_LIGHT_SINGLE: i32 = eShaderType::DEFERRED_LIGHT_SINGLE as i32;
pub const DEFERRED_LIGHT_DOUBLE: i32 = eShaderType::DEFERRED_LIGHT_DOUBLE as i32;
pub const DEFERRED_LIGHT_TRIPLE: i32 = eShaderType::DEFERRED_LIGHT_TRIPLE as i32;
pub const DEFERRED_PLANAR_EVAL: i32 = eShaderType::DEFERRED_PLANAR_EVAL as i32;
pub const DEFERRED_THICKNESS_AMEND: i32 = eShaderType::DEFERRED_THICKNESS_AMEND as i32;
pub const DEFERRED_TILE_CLASSIFY: i32 = eShaderType::DEFERRED_TILE_CLASSIFY as i32;
pub const DEFERRED_TILE_CLASSIFY_FALLBACK: i32 = eShaderType::DEFERRED_TILE_CLASSIFY_FALLBACK as i32;
pub const DEBUG_GBUFFER: i32 = eShaderType::DEBUG_GBUFFER as i32;
pub const DEBUG_SURFELS: i32 = eShaderType::DEBUG_SURFELS as i32;
pub const DEBUG_IRRADIANCE_GRID: i32 = eShaderType::DEBUG_IRRADIANCE_GRID as i32;
pub const DISPLAY_PROBE_VOLUME: i32 = eShaderType::DISPLAY_PROBE_VOLUME as i32;
pub const DISPLAY_PROBE_SPHERE: i32 = eShaderType::DISPLAY_PROBE_SPHERE as i32;
pub const DISPLAY_PROBE_PLANAR: i32 = eShaderType::DISPLAY_PROBE_PLANAR as i32;
pub const DOF_BOKEH_LUT: i32 = eShaderType::DOF_BOKEH_LUT as i32;
pub const DOF_DOWNSAMPLE: i32 = eShaderType::DOF_DOWNSAMPLE as i32;
pub const DOF_FILTER: i32 = eShaderType::DOF_FILTER as i32;
pub const DOF_GATHER_BACKGROUND_LUT: i32 = eShaderType::DOF_GATHER_BACKGROUND_LUT as i32;
pub const DOF_GATHER_BACKGROUND: i32 = eShaderType::DOF_GATHER_BACKGROUND as i32;
pub const DOF_GATHER_FOREGROUND_LUT: i32 = eShaderType::DOF_GATHER_FOREGROUND_LUT as i32;
pub const DOF_GATHER_FOREGROUND: i32 = eShaderType::DOF_GATHER_FOREGROUND as i32;
pub const DOF_GATHER_HOLE_FILL: i32 = eShaderType::DOF_GATHER_HOLE_FILL as i32;
pub const DOF_REDUCE: i32 = eShaderType::DOF_REDUCE as i32;
pub const DOF_RESOLVE_LUT: i32 = eShaderType::DOF_RESOLVE_LUT as i32;
pub const DOF_RESOLVE: i32 = eShaderType::DOF_RESOLVE as i32;
pub const DOF_SCATTER: i32 = eShaderType::DOF_SCATTER as i32;
pub const DOF_SETUP: i32 = eShaderType::DOF_SETUP as i32;
pub const DOF_STABILIZE: i32 = eShaderType::DOF_STABILIZE as i32;
pub const DOF_TILES_DILATE_MINABS: i32 = eShaderType::DOF_TILES_DILATE_MINABS as i32;
pub const DOF_TILES_DILATE_MINMAX: i32 = eShaderType::DOF_TILES_DILATE_MINMAX as i32;
pub const DOF_TILES_FLATTEN: i32 = eShaderType::DOF_TILES_FLATTEN as i32;
pub const HIZ_UPDATE: i32 = eShaderType::HIZ_UPDATE as i32;
pub const HIZ_UPDATE_LAYER: i32 = eShaderType::HIZ_UPDATE_LAYER as i32;
pub const HIZ_DEBUG: i32 = eShaderType::HIZ_DEBUG as i32;
pub const FAST_GI_DENOISE: i32 = eShaderType::FAST_GI_DENOISE as i32;
pub const FAST_GI_RESOLVE: i32 = eShaderType::FAST_GI_RESOLVE as i32;
pub const FAST_GI_SCAN: i32 = eShaderType::FAST_GI_SCAN as i32;
pub const FAST_GI_SETUP: i32 = eShaderType::FAST_GI_SETUP as i32;
pub const LIGHT_CULLING_DEBUG: i32 = eShaderType::LIGHT_CULLING_DEBUG as i32;
pub const LIGHT_CULLING_SELECT: i32 = eShaderType::LIGHT_CULLING_SELECT as i32;
pub const LIGHT_CULLING_SORT: i32 = eShaderType::LIGHT_CULLING_SORT as i32;
pub const LIGHT_CULLING_TILE: i32 = eShaderType::LIGHT_CULLING_TILE as i32;
pub const LIGHT_CULLING_ZBIN: i32 = eShaderType::LIGHT_CULLING_ZBIN as i32;
pub const LIGHT_SHAPE_DISPLAY: i32 = eShaderType::LIGHT_SHAPE_DISPLAY as i32;
pub const LIGHT_SHADOW_SETUP: i32 = eShaderType::LIGHT_SHADOW_SETUP as i32;
pub const LIGHTPROBE_IRRADIANCE_BOUNDS: i32 = eShaderType::LIGHTPROBE_IRRADIANCE_BOUNDS as i32;
pub const LIGHTPROBE_IRRADIANCE_OFFSET: i32 = eShaderType::LIGHTPROBE_IRRADIANCE_OFFSET as i32;
pub const LIGHTPROBE_IRRADIANCE_RAY: i32 = eShaderType::LIGHTPROBE_IRRADIANCE_RAY as i32;
pub const LIGHTPROBE_IRRADIANCE_LOAD: i32 = eShaderType::LIGHTPROBE_IRRADIANCE_LOAD as i32;
pub const LIGHTPROBE_IRRADIANCE_WORLD: i32 = eShaderType::LIGHTPROBE_IRRADIANCE_WORLD as i32;
pub const LOOKDEV_COPY_WORLD: i32 = eShaderType::LOOKDEV_COPY_WORLD as i32;
pub const LOOKDEV_DISPLAY: i32 = eShaderType::LOOKDEV_DISPLAY as i32;
pub const MOTION_BLUR_GATHER: i32 = eShaderType::MOTION_BLUR_GATHER as i32;
pub const MOTION_BLUR_TILE_DILATE: i32 = eShaderType::MOTION_BLUR_TILE_DILATE as i32;
pub const MOTION_BLUR_TILE_FLATTEN_RGBA: i32 = eShaderType::MOTION_BLUR_TILE_FLATTEN_RGBA as i32;
pub const MOTION_BLUR_TILE_FLATTEN_RG: i32 = eShaderType::MOTION_BLUR_TILE_FLATTEN_RG as i32;
pub const RAY_DENOISE_BILATERAL: i32 = eShaderType::RAY_DENOISE_BILATERAL as i32;
pub const RAY_DENOISE_SPATIAL: i32 = eShaderType::RAY_DENOISE_SPATIAL as i32;
pub const RAY_DENOISE_TEMPORAL: i32 = eShaderType::RAY_DENOISE_TEMPORAL as i32;
pub const RAY_GENERATE: i32 = eShaderType::RAY_GENERATE as i32;
pub const RAY_TILE_CLASSIFY: i32 = eShaderType::RAY_TILE_CLASSIFY as i32;
pub const RAY_TILE_COMPACT: i32 = eShaderType::RAY_TILE_COMPACT as i32;
pub const RAY_TRACE_FALLBACK: i32 = eShaderType::RAY_TRACE_FALLBACK as i32;
pub const RAY_TRACE_PLANAR: i32 = eShaderType::RAY_TRACE_PLANAR as i32;
pub const RAY_TRACE_SCREEN: i32 = eShaderType::RAY_TRACE_SCREEN as i32;
pub const RENDERPASS_CLEAR: i32 = eShaderType::RENDERPASS_CLEAR as i32;
pub const SPHERE_PROBE_CONVOLVE: i32 = eShaderType::SPHERE_PROBE_CONVOLVE as i32;
pub const SPHERE_PROBE_IRRADIANCE: i32 = eShaderType::SPHERE_PROBE_IRRADIANCE as i32;
pub const SPHERE_PROBE_REMAP: i32 = eShaderType::SPHERE_PROBE_REMAP as i32;
pub const SPHERE_PROBE_SELECT: i32 = eShaderType::SPHERE_PROBE_SELECT as i32;
pub const SPHERE_PROBE_SUNLIGHT: i32 = eShaderType::SPHERE_PROBE_SUNLIGHT as i32;
pub const SHADOW_CLIPMAP_CLEAR: i32 = eShaderType::SHADOW_CLIPMAP_CLEAR as i32;
pub const SHADOW_DEBUG: i32 = eShaderType::SHADOW_DEBUG as i32;
pub const SHADOW_PAGE_ALLOCATE: i32 = eShaderType::SHADOW_PAGE_ALLOCATE as i32;
pub const SHADOW_PAGE_CLEAR: i32 = eShaderType::SHADOW_PAGE_CLEAR as i32;
pub const SHADOW_PAGE_DEFRAG: i32 = eShaderType::SHADOW_PAGE_DEFRAG as i32;
pub const SHADOW_PAGE_FREE: i32 = eShaderType::SHADOW_PAGE_FREE as i32;
pub const SHADOW_PAGE_MASK: i32 = eShaderType::SHADOW_PAGE_MASK as i32;
pub const SHADOW_TILEMAP_AMEND: i32 = eShaderType::SHADOW_TILEMAP_AMEND as i32;
pub const SHADOW_TILEMAP_BOUNDS: i32 = eShaderType::SHADOW_TILEMAP_BOUNDS as i32;
pub const SHADOW_TILEMAP_FINALIZE: i32 = eShaderType::SHADOW_TILEMAP_FINALIZE as i32;
pub const SHADOW_TILEMAP_RENDERMAP: i32 = eShaderType::SHADOW_TILEMAP_RENDERMAP as i32;
pub const SHADOW_TILEMAP_INIT: i32 = eShaderType::SHADOW_TILEMAP_INIT as i32;
pub const SHADOW_TILEMAP_TAG_UPDATE: i32 = eShaderType::SHADOW_TILEMAP_TAG_UPDATE as i32;
pub const SHADOW_TILEMAP_TAG_UPDATE_PROPAGATE: i32 = eShaderType::SHADOW_TILEMAP_TAG_UPDATE_PROPAGATE as i32;
pub const SHADOW_TILEMAP_TAG_USAGE_OPAQUE: i32 = eShaderType::SHADOW_TILEMAP_TAG_USAGE_OPAQUE as i32;
pub const SHADOW_TILEMAP_TAG_USAGE_SURFELS: i32 = eShaderType::SHADOW_TILEMAP_TAG_USAGE_SURFELS as i32;
pub const SHADOW_TILEMAP_TAG_USAGE_TRANSPARENT: i32 = eShaderType::SHADOW_TILEMAP_TAG_USAGE_TRANSPARENT as i32;
pub const SHADOW_TILEMAP_TAG_USAGE_VOLUME: i32 = eShaderType::SHADOW_TILEMAP_TAG_USAGE_VOLUME as i32;
pub const SHADOW_VIEW_VISIBILITY: i32 = eShaderType::SHADOW_VIEW_VISIBILITY as i32;
pub const SUBSURFACE_CONVOLVE: i32 = eShaderType::SUBSURFACE_CONVOLVE as i32;
pub const SUBSURFACE_SETUP: i32 = eShaderType::SUBSURFACE_SETUP as i32;
pub const SURFEL_CLUSTER_BUILD: i32 = eShaderType::SURFEL_CLUSTER_BUILD as i32;
pub const SURFEL_LIGHT: i32 = eShaderType::SURFEL_LIGHT as i32;
pub const SURFEL_LIST_BUILD: i32 = eShaderType::SURFEL_LIST_BUILD as i32;
pub const SURFEL_LIST_FLATTEN: i32 = eShaderType::SURFEL_LIST_FLATTEN as i32;
pub const SURFEL_LIST_PREFIX: i32 = eShaderType::SURFEL_LIST_PREFIX as i32;
pub const SURFEL_LIST_PREPARE: i32 = eShaderType::SURFEL_LIST_PREPARE as i32;
pub const SURFEL_LIST_SORT: i32 = eShaderType::SURFEL_LIST_SORT as i32;
pub const SURFEL_RAY: i32 = eShaderType::SURFEL_RAY as i32;
pub const TRANSPARENCY_RESOLVE: i32 = eShaderType::TRANSPARENCY_RESOLVE as i32;
pub const VERTEX_COPY: i32 = eShaderType::VERTEX_COPY as i32;
pub const VOLUME_INTEGRATION: i32 = eShaderType::VOLUME_INTEGRATION as i32;
pub const VOLUME_OCCUPANCY_CONVERT: i32 = eShaderType::VOLUME_OCCUPANCY_CONVERT as i32;
pub const VOLUME_RESOLVE: i32 = eShaderType::VOLUME_RESOLVE as i32;
pub const VOLUME_SCATTER: i32 = eShaderType::VOLUME_SCATTER as i32;
pub const VOLUME_SCATTER_WITH_LIGHTS: i32 = eShaderType::VOLUME_SCATTER_WITH_LIGHTS as i32;
pub const MAX_SHADER_TYPE: i32 = eShaderType::MAX_SHADER_TYPE as i32;

#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShaderGroups {
    NONE = 0,
    DEFERRED_LIGHTING_SHADERS = 1 << 0,
    DEFERRED_CAPTURE_SHADERS = 1 << 1,
    DEFERRED_PLANAR_SHADERS = 1 << 2,
    DEPTH_OF_FIELD_SHADERS = 1 << 3,
    HIZ_SHADERS = 1 << 4,
    FAST_GI_SHADERS = 1 << 5,
    LIGHT_CULLING_SHADERS = 1 << 6,
    IRRADIANCE_BAKE_SHADERS = 1 << 7,
    SPHERE_PROBE_SHADERS = 1 << 8,
    SHADOW_SHADERS = 1 << 9,
    AMBIENT_OCCLUSION_SHADERS = 1 << 10,
    MOTION_BLUR_SHADERS = 1 << 11,
    RAYTRACING_SHADERS = 1 << 12,
    FILM_SHADERS = 1 << 13,
    SUBSURFACE_SHADERS = 1 << 14,
    SURFEL_SHADERS = 1 << 15,
    VERTEX_COPY_SHADERS = 1 << 16,
    VOLUME_EVAL_SHADERS = 1 << 17,
    DEFAULT_MATERIALS = 1 << 18,
    WORLD_SHADERS = 1 << 19,
    MATERIAL_SHADERS = 1 << 20,
    VOLUME_PROBE_SHADERS = 1 << 21,
}

impl Default for ShaderGroups {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}

pub const NONE: i32 = ShaderGroups::NONE as i32;
pub const DEFERRED_LIGHTING_SHADERS: i32 = ShaderGroups::DEFERRED_LIGHTING_SHADERS as i32;
pub const DEFERRED_CAPTURE_SHADERS: i32 = ShaderGroups::DEFERRED_CAPTURE_SHADERS as i32;
pub const DEFERRED_PLANAR_SHADERS: i32 = ShaderGroups::DEFERRED_PLANAR_SHADERS as i32;
pub const DEPTH_OF_FIELD_SHADERS: i32 = ShaderGroups::DEPTH_OF_FIELD_SHADERS as i32;
pub const HIZ_SHADERS: i32 = ShaderGroups::HIZ_SHADERS as i32;
pub const FAST_GI_SHADERS: i32 = ShaderGroups::FAST_GI_SHADERS as i32;
pub const LIGHT_CULLING_SHADERS: i32 = ShaderGroups::LIGHT_CULLING_SHADERS as i32;
pub const IRRADIANCE_BAKE_SHADERS: i32 = ShaderGroups::IRRADIANCE_BAKE_SHADERS as i32;
pub const SPHERE_PROBE_SHADERS: i32 = ShaderGroups::SPHERE_PROBE_SHADERS as i32;
pub const SHADOW_SHADERS: i32 = ShaderGroups::SHADOW_SHADERS as i32;
pub const AMBIENT_OCCLUSION_SHADERS: i32 = ShaderGroups::AMBIENT_OCCLUSION_SHADERS as i32;
pub const MOTION_BLUR_SHADERS: i32 = ShaderGroups::MOTION_BLUR_SHADERS as i32;
pub const RAYTRACING_SHADERS: i32 = ShaderGroups::RAYTRACING_SHADERS as i32;
pub const FILM_SHADERS: i32 = ShaderGroups::FILM_SHADERS as i32;
pub const SUBSURFACE_SHADERS: i32 = ShaderGroups::SUBSURFACE_SHADERS as i32;
pub const SURFEL_SHADERS: i32 = ShaderGroups::SURFEL_SHADERS as i32;
pub const VERTEX_COPY_SHADERS: i32 = ShaderGroups::VERTEX_COPY_SHADERS as i32;
pub const VOLUME_EVAL_SHADERS: i32 = ShaderGroups::VOLUME_EVAL_SHADERS as i32;
pub const DEFAULT_MATERIALS: i32 = ShaderGroups::DEFAULT_MATERIALS as i32;
pub const WORLD_SHADERS: i32 = ShaderGroups::WORLD_SHADERS as i32;
pub const MATERIAL_SHADERS: i32 = ShaderGroups::MATERIAL_SHADERS as i32;
pub const VOLUME_PROBE_SHADERS: i32 = ShaderGroups::VOLUME_PROBE_SHADERS as i32;
